config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root 'main#index'
  resources :tasks
  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    if user.role?(:admin)
      can :manage, :all
    elsif user.role?(:user)
      can :manage, [Project, Task], user_id: user.id
    else
      # set role by default
      cannot :manage, :all
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

# ApplicationRecord comment
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
# frozen_string_literal: true

# This keep projects
class Project < ApplicationRecord
  has_many :tasks, dependent: :delete_all

  validates :name, presence: true

  # default scope
  scope :default, -> {
    order('projects.created_at')
      .includes(:tasks)
      .order('tasks.position')
  }

  # get the count of all tasks in each project, order by tasks count desc
  scope :tasks_count_order_tasks_count, -> {
    left_joins(:tasks)
      .select('projects.name')
      .group('projects.name')
      .order('count(tasks.id) desc')
      .count('tasks.id')
  }

  # get the count of all tasks in each project, order by projects names
  scope :tasks_count_order_projects_names, -> {
    left_joins(:tasks)
      .select('projects.name')
      .group('projects.name')
      .order('projects.name')
      .count('tasks.id')
  }

  # get the list of all projects containing the letter in the middle of the name
  scope :projects_contain_middle, ->(letter = 'a') {
    joins('full outer join tasks on tasks.project_id = projects.id')
      .select('projects.name')
      .where('projects.name like :project_name', project_name: "%#{letter}%")
      .group('projects.name')
      .count('tasks.id')
  }

  # get the list of project names having more than 10 tasks in status 'completed'.
  # order by project_id
  scope :project_names_more_10_tasks, -> {
    left_joins(:tasks)
      .select('projects.id, projects.name')
      .where('tasks.status = :completed', completed: Task::COMPLETED)
      .group('projects.id' ,'projects.name')
      .having('count(tasks.status) > 5')
      .order('projects.id')
      .pluck('name')
  }
end

app/models/task.rb
# frozen_string_literal: true

# This keep project tasks
class Task < ApplicationRecord
  belongs_to :project

  NORMAL = 1
  ACTIVE = 2
  COMPLETED = 3

  STATUSES = {
    NORMAL => 'normal',
    ACTIVE => 'active',
    COMPLETED => 'completed'
  }.freeze

  validates :name, presence: true
  validates_inclusion_of :status, in: STATUSES.keys,
                                  message: "{{value}} must be in: #{STATUSES.values.join ','}"

  # get all statuses, not repeating, alphabetically ordered
  scope :all_statuses_not_repeat_sorted, -> {
    select(:status)
      .distinct
      .pluck('status')
      .map{ |k| STATUSES[k] }
      .sort
  }

  # get the tasks for all projects having the name beginning with letter
  scope :tasks_begin_with, ->(letter = 'N') {
    select('tasks.name')
      .where('tasks.name like :task_name', task_name: "#{letter}%")
  }

  # get the list of tasks with duplicate names. order alphabetically
  scope :tasks_duplicated_names, -> {
    select('name')
      .group('name')
      .order('name')
      .having('count(name) > 1')
  }

  # get the list of tasks having several matches of both name and status.
  # order by matches count
  scope :tasks_matches_name_status, ->(project_name = 'Garage') {
    left_joins(:project)
      .where('projects.name = :project_name', project_name: "#{project_name}")
      .group('tasks.name', 'tasks.status')
      .order('count(tasks.name)')
      .having('count(tasks.name) > 1')
      .count()
  }

  # helper method for view
  def status_name
    STATUSES[status]
  end

  def self.get_by_status(status)
    all.select do |task|
      task.status == status
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_initialize :default_role

  ROLES = { 0 => :guest, 1 => :user, 2 => :admin }.freeze

  def role?(role_name)
    ROLES[role] == role_name
  end

  private

  def default_role(role = 1)
    self.role = role
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Global application methods
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/main_controller.rb
# frozen_string_literal: true

# MainController comment
class MainController < ApplicationController
  def index
    @projects = Project.default
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

# ProjectsController comment
class ProjectsController < ApplicationController
  load_and_authorize_resource

  def new
    @project = Project.new
    respond_to do |format|
      format.js
    end
  end

  def create
    project = Project.new(project_params)
    project.user_id = current_user.id unless current_user.nil?
    if project.save
      redirect_to root_url
    else
      render json: task.errors, status: :unprocessable_entity
    end
  end

  def edit
    @project = Project.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def update
    @project = Project.find(params[:id])
    @project.update(project_params)
    redirect_to root_url
  end

  def destroy
    @project = Project.find(params[:id]).destroy
    redirect_to root_url
  end

  private

  def project_params
    params.require(:project).permit(:id, :name, :user_id)
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

# TasksController comment
class TasksController < ApplicationController
  load_and_authorize_resource

  def new
    @task = Task.new
    respond_to do |format|
      format.js
    end
  end

  def create
    task = Task.new(task_params)
    task.user_id = current_user.id unless current_user.nil?
    if task.save
      redirect_to root_url
    else
      render json: task.errors, status: :unprocessable_entity
    end
  end

  def edit
    @task = Task.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def update
    @task = Task.find(params[:id])
    puts "task: #{@task}, task_params: #{task_params}"
    @task.update(task_params)
    if params[:commit].nil? # xhr
      render json: { name: @task.name, status: Task::STATUSES[@task.status] }, status: :ok
    else
      redirect_to root_url
    end
  end

  def destroy
    @task = Task.find(params[:id]).destroy
    redirect_to root_url
  end

  private

  def task_params
    params.require(:task).permit(:id, :name, :status, :project_id, :deadline, :position, :user_id)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDo - Andriy Koval</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <div class="b-wrap">
      <div class="text-center">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </div>

      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<h1 class="text-center">Simple ToDo List</h1>

<div class="b-projects">

  <% @projects.each do |project| %>

    <% if can? :manage, project %>

    <div class="panel panel-primary">

      <% # project header %>
      <div class="panel-heading">
        <i class="glyphicon glyphicon-list-alt mx-5"></i>
        <div class="b-pr-title">
          <%= project.name %>
        </div>
        <div class=" pull-right">
          <%= link_to edit_project_path(project), remote: true do %>
            <i class="glyphicon glyphicon-pencil mx-5"></i>
          <% end %>
          <%= link_to project_path(project), data: {confirm: 'Delete project?'}, method: 'delete', remote: true do %>
            <i class="glyphicon glyphicon-trash mx-5"></i>
          <% end %>
        </div>
      </div>

      <% # add new task %>
      <div class="panel-footer b-add-task">
        <div class="input-group">
          <%= form_for Task.new, html: {id: "new_task_" + project.id.to_s, class: "b-new-task form-horizontal"}, data: {'project-id': project.id.to_s}, remote: true do |t| %>
            <%= t.hidden_field :project_id, id: "task_project_id_" + project.id.to_s, value: project.id %>
            <div class="input-group addon">
              <span class="input-group-addon">
                <i class="fa fa-plus text-success"></i>
              </span>
              <%= t.text_field :name, id: "task_name_" + project.id.to_s, class: "form-control", required: true, placeholder: "Start typing here to create a task..." %>
              <div class="input-group-btn">
                <%#= link_to "Add Task", new_task_path, remote: true, class: "btn btn-success" %>
                <%= t.submit "Add Task", class: "btn btn-success" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>

      <% # task list %>
      <div class="panel-body b-tasks">
        <ul class="sortable-tasks" id="sortable-tasks-<%= project.id.to_s %>">
        <% project.tasks.each do |task| %>
          <li class="b-task" data-id="<%= task.id %>" data-position="<%= task.position %>">
            <div class="col1 invisible">
              <div class="t-col-chb">
                <label>
                  <input type="checkbox" data-id="<%= task.id %>"
                    <%= task.status == Task::COMPLETED ? 'checked' : '' %>>
                </label>
              </div>
            </div>

            <div class="col3">
              <div class="t-col-info">
                <div class="task-title">
                  <%= task.name %> (<%= task.status_name %>)
                </div>
              </div>
            </div>

            <div class="col4 invisible text-right">
              <div class="t-col-btns">
                <a href="#"><i class="glyphicon glyphicon-move mx-5"></i></a>
                <%= link_to edit_task_path(task), remote: true do %><i class="glyphicon glyphicon-pencil mx-5"></i><% end %>
                <%= link_to task_path(task), data: {confirm: 'Delete task?'}, method: 'delete', remote: true do %><i class="glyphicon glyphicon-trash mx-5"></i><% end %>
              </div>
            </div>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
    <% end %>

  <% end %>

</div>

<div class="b-add-project text-center">
  <%= link_to "Add ToDo List", new_project_path, remote: true, class: "btn btn-primary" %>
</div>

<div id="project-new"></div>
<div id="task-new"></div>

app/views/projects/_new.html.erb
<div class="row top15">
  <%= form_for project, html: {class: "form-horizontal"}, remote: true do |p| %>
    <div class="form-group">
      <%= p.label :name, "Name:", class: "control-label col-sm-2" %>
      <div class="col-sm-8">
        <%= p.text_field :name, class: "form-control", required: true, value: project.name %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-6">
        <%= p.submit project.new_record? ? "Create Project": "Update Project", class: "btn btn-success" %>
      </div>
    </div>
  <% end %>
</div>

app/views/projects/_project_modal.html.erb
<div id="project-modal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <div>
        <%= render partial: 'projects/new', locals: { project: project } %>
      </div>
    </div>
  </div>
</div>

app/views/projects/edit.js.erb
$('#project-new').html("<%= j render 'project_modal', project: @project %>");
$('#project-modal').modal('show');

app/views/projects/new.js.erb
$('#project-new').html("<%= j render 'project_modal', project: @project %>");
$('#project-modal').modal('show');

app/views/tasks/_new.html.erb
<div class="row top15">
  <%= form_for task, html: {class: "form-horizontal"}, remote: true do |t| %>
    <div class="form-group">
      <%= t.label :name, "Name:", class: "control-label col-sm-2" %>
      <div class="col-sm-8">
        <%= t.text_field :name, class: "form-control", required: true, value: task.name %>
      </div>
    </div>
    <div class="form-group">
      <%= t.label :status, "Status:", class: "control-label col-sm-2" %>
      <div class="col-sm-8">
        <%= t.select :status, Task::STATUSES.invert, {}, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= t.label :project_id, "Project:", class: "control-label col-sm-2" %>
      <div class="col-sm-8">
        <%= t.select :project_id, Project.all.map{|p| [p.name, p.id]}, {}, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <%= t.label :deadline, "Deadline:", class: "control-label col-sm-2" %>
      <div class="col-sm-8">
        <%= t.text_field :deadline, data: {provide: 'datepicker'}, class: "form-control" %>
        <%#= t.text_field :deadline, class: "datepicker" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-6">
        <%= t.submit task.new_record? ? "Create Task": "Update Task", class: "btn btn-success" %>
      </div>
    </div>
  <% end %>
</div>

app/views/tasks/_task_modal.html.erb
<div id="task-modal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <div>
        <%= render partial: 'tasks/new', locals: { task: task } %>
      </div>
    </div>
  </div>
</div>

app/views/tasks/edit.js.erb
$('#task-new').html("<%= j render 'task_modal', task: @task %>");
$('#task-modal').modal('show');

app/views/tasks/new.js.erb
$('#task-new').html("<%= j render 'task_modal', task: @task %>");
$('#task-modal').modal('show');